name: whatami
adopt-info: whatami
summary: You better have thick skin...or a thick skull!
description: |
  You came here for help and you found the opposite! Get ready for a litany of insults; 
  insults that your terminal has always _wanted_ to say but never had the permission.
  Now, it doesn't care.

  **Submit new insults!**

    https://github.com/kz6fittycent/whatami/issues

    or

    https://github.com/kz6fittycent/whatami/pulls

  **Install the snap**

    sudo snap install whatami
    
  **Run it**
    
    With ascii - whatami
    
    Without ascii - whatami -p
    
  **Disclaimer**

    You use this snap and software of your own accord, free will and choice. 
    No one forced you to install it and take these insults. 
    This software is meant for those with thick skin and a masochistic nature. 
    Basically, people who don't take life seriously - nor themselves.

    Just take a step back and laugh at yourself once in a while, everyone else is! :P
    
      
grade: stable 
confinement: strict 
base: core18

license: MIT

apps:
  whatami:
    command: whatami
    environment:
      LC_ALL: C.UTF-8

parts: 
  whatami:
    source: https://github.com/kz6fittycent/whatami
    source-type: git
    plugin: python
    python-version: python3

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
      
    build-packages:
      - python3
     
    stage-packages:
      - python3
